### ISSUE TITLE
请问怎么用啊

### ISSUE THREAD

**Issue by SnowStorm-L** [cfrs2005/lcg-php#3]
我不是做php开发的

APP_ID
API_KEY
SECRET_KEY  都填完了

cookie 要填东西吗?

代码18行  出现了错误 改成这样吗?
if(!isset($output[0])){
	exit();
}

我现在的环境是mac book 

然后按照http://blog.csdn.net/wenxiangjiang/article/details/52651366  
的连接开了Apache 

在配置路径下成功打开了这个链接的info.php     http://localhost/info.php

我把你的dog.php 也按照  http://localhost/dog.php 的做法打开一片空白

终端执行完后

php dog.php
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3418    0  3264  100   154  15836    747 --:--:-- --:--:-- --:--:-- 15844

请教一下接下来怎么做?

**Comment by cfrs2005** [comment]
不需要apache

直接 终端输入  php xxx.php 即可 .

一般  brew install php 就可以搞定环境

另外cookie不管你是啥开发都应该知道是什么。 通过浏览器直接抓一个就了

**Comment by SnowStorm-L** [comment]
我终端  输入 php dog.php 之后就这个样子 
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3418    0  3264  100   154  13471    635 --:--:-- --:--:-- --:--:-- 13487

或者

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3415    0  3261  100   154  13452    635 --:--:-- --:--:-- --:--:-- 13419
https://pet-chain.baidu.com/chain/detail?channel=market&petId=1855391924450761409&validCode=26e289b3b75f6aa12b0cfb94b1ae2a67
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   112  100    64  100    48    283    212 --:--:-- --:--:-- --:--:--   284
array(3) {
  ["log_id"]=>
  int(3566445301328990516)
  ["error_code"]=>
  int(216200)
  ["error_msg"]=>
  string(11) "empty image"
}
NULL

然后没其他反应了.  大概是什么情况呢?

终端 php -v

PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

php环境应该是搭好了吧?

**Comment by SnowStorm-L** [comment]
2018-02-06 09:42:05	黑产 百度 pet-chain
2018-02-06 09:42:05	当前价格最大限制为:	1000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3419    0  3265  100   154  11619    548 --:--:-- --:--:-- --:--:-- 11619
2018-02-06 09:42:06	1861769950887980276	价格:	2000.00
2018-02-06 09:42:06	1855391752652067059	价格:	2150.00
2018-02-06 09:42:06	1858370157854372028	价格:	2150.00
2018-02-06 09:42:06	1855451676035899662	价格:	2170.00
2018-02-06 09:42:06	1861775104848913287	价格:	2175.00
2018-02-06 09:42:06	1861766274395942319	价格:	2175.00
2018-02-06 09:42:06	1855391924450757177	价格:	2176.00
2018-02-06 09:42:06	1855391958810495096	价格:	2178.00
2018-02-06 09:42:06	1858369573738794207	价格:	2178.00
2018-02-06 09:42:06	1858365519289548073	价格:	2178.88

有数据输出了  这样就是可以了吗?  有什么可以设置的条件,除了当前价格最大限制为

**Comment by cfrs2005** [comment]
可以了，max_amount 改下即可，目前 pet-chain不支持 分页数量修改，验证码 百度的ocr 还是不行 得换一个 命中率 至少我目前看来是0%

**Comment by SnowStorm-L** [comment]
感谢你的热心帮助,我会持续关注的  已经start了
