### ISSUE TITLE
cookie如何设置

### ISSUE THREAD

**Issue by HavenLiu** [cfrs2005/lcg-php#5]
能否给一个cookie的示例？

**Comment by cfrs2005** [comment]
chrome  请求url  ,打开 调试模式 ，随便抓个百度的请求，里面head中有个cookie

**Comment by cfrs2005** [comment]
__cfduid=＊＊; BAIDUID=＊＊:FG=1; PSTM=＊＊; BIDUPSID=＊＊; MCITY=-%3A; BDUSS=＊＊; BDORZ=＊＊; H_PS_PSSID=＊＊; BDRCVFR[＊＊]=＊＊; PSINO=5; BCLID=＊＊;

**Comment by HavenLiu** [comment]
知道了。开始我用chrome插件复制出来的cookie不对，谢谢
