### ISSUE TITLE
curl 报错

### ISSUE THREAD

**Issue by cuican008** [cfrs2005/lcg-php#7]
curl: (1) Protocol 'https not supported or disabled in libcurl

curl: (1) Protocol https not supported or disabled in libcurl

curl: (6) Could not resolve host: gzip,; Host not found

curl: (6) Could not resolve host: deflate,; Host not found

curl: (6) Could not resolve host: br'; Host not found

curl: (6) Could not resolve host: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6'; Host not found

curl: (6) Could not resolve host: Mozilla; Host not found

curl: (6) Could not resolve host: (Macintosh;; Host not found

curl: (6) Could not resolve host: Intel; Host not found

curl: (6) Could not resolve host: Mac; Host not found

curl: (6) Could not resolve host: OS; Host not found

curl: (6) Could not resolve host: X; Host not found

curl: (6) Could not resolve host: 10_11_4); Host not found

**Comment by cfrs2005** [comment]
https://github.com/coneo/blog/issues/19

**Comment by cuican008** [comment]
curl: (1) Protocol "'https" not supported or disabled in libcurl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: pet-chain.baidu.com'
curl: (6) Could not resolve host: gzip,
curl: (6) Could not resolve host: deflate,
curl: (6) Could not resolve host: br'
curl: (6) Could not resolve host: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6'
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0curl: (6) Could not resolve host: Mozilla
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: (Macintosh;
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: Intel
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: Mac
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: OS
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: X
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 10_11_4)
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: AppleWebKit
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: (KHTML,
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0curl: (6) Could not resolve host: like
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: Gecko)
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: Chrome
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: Safari
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: application
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: application
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: pet-chain.baidu.com'
curl: (3) Port number ended with 'F'
curl: (6) Could not resolve host: PSTM=151#########049;
curl: (6) Could not resolve host: BIDUPSID=608D#############06136F6;
curl: (6) Could not resolve host: BDUSS=jFlM2pqeEY3SlN#############9CNG9mRG9-NkZhQUFBQUFBJCQA####################yelrocnpaY;
curl: (6) Could not resolve host: PSINO=3;
curl: (6) Could not resolve host: BCLID=14120#######6210;
curl: (6) Could not resolve host: BDSFRCVID=S78sJ##########Kome7YxVCP-QTH6aoUWSSBZNRG#############0Kub55HBogKKLgOTHUQP;
curl: (6) Could not resolve host: H_BDCLCKID_SF=t###################Hen-fqnJZ5mAqoq3nJnQphpjIhMcvhPu8jnrOLf##################_mDU5;
curl: (6) Could not resolve host: BDRCVFR**********;
curl: (6) Could not resolve host: H_PS_PSSID=**************;
curl: (6) Could not resolve host: BDORZ=*********'
curl: (6) Could not resolve host: keep-alive'
2018-02-07 06:37:26     empty respone

**Comment by cuican008** [comment]
我用的是win10

**Comment by cfrs2005** [comment]
换个 安装包? 我不再windows下开发  或者 问下谷歌

**Comment by cuican008** [comment]
感谢我更换一下linux

**Comment by cuican008** [comment]
更换linux  后 提示 
PHP Notice:  Undefined variable: output in /root/lcg-php-master/dog.php on line 27
PHP Notice:  Undefined variable: return_arr in /root/lcg-php-master/dog.php on line 27
PHP Warning:  exec() has been disabled for security reasons in /root/lcg-php-master/dog.php on line 27

**Comment by cfrs2005** [comment]
编辑下 你的php.ini exec 被禁用了

**Comment by cuican008** [comment]
搞定了 感谢楼主 已star

**Comment by cuican008** [comment]
2018-02-07 15:06:10     1855452260151483067     ä»·æ ¼: 1898.99
2018-02-07 15:06:10     1855389003872995029     ä»·æ ¼: 1899.00
2018-02-07 15:06:10     1855392096249453535     ä»·æ ¼: 1899.00
2018-02-07 15:06:10     1855392130609190208     ä»·æ ¼: 1899.00
2018-02-07 15:06:10     1857944887371528992     ä»·æ ¼: 1899.99
2018-02-07 15:06:10     1855389038232736928     ä»·æ ¼: 1900.00
2018-02-07 15:06:10     1855392302407877727     ä»·æ ¼: 1900.00
2018-02-07 15:06:10     1855392302407883102     ä»·æ ¼: 1900.00
2018-02-07 15:06:10     1855392336767617203     ä»·æ ¼: 1900.00
2018-02-07 15:06:10     1855392405487093951     ä»·æ ¼: 1900.00

**Comment by cuican008** [comment]
貌似不是自动化的 要手动刷新，加个循环可好？

**Comment by cfrs2005** [comment]
````
crontab -e
* * * * * sleep 10;php dog >> xx.log
* * * * * sleep 20;php dog >> xx.log
* * * * * sleep 30;php dog >> xx.log
````
